#!/usr/bin/env bash
#Bash script that changes IP addresses of localhost and facebook as found in /etc/hosts

#To achieve this, create a backup file with copied /etc/hosts file content
#Then apply changes to this backup before effecting complete change on oriinal /etc/hosts file

cp /etc/hosts ~/hosts_backup
echo "127.0.0.2              localhost" > ~/hosts_backup
echo "8.8.8.8                facebook.com" >> ~/hosts_backup
cp -f ~/hosts_backup /etc/hosts
