#!/usr/bin/env bash
#Script that displays all active IPv4 addresses 

#ifconfig is a command that details active network interfaces
#Part of the details of active interfaces listed is the IP addresses
#Which can be found at the seconnd field on lines starting with 'inet'

ifconfig | grep 'inet ' | grep -v 'inet6' | awk '{print $2}'
